language: haskell

ghc:
#  - '7.10'
  - 7.8
  - 7.6

#Overwrite the test script, since we don't have any tests
script: cabal install --flags with-mpd --only-dependencies && cabal configure --flags with-mpd && cabal build
